// Mock data for UI development - set USE_MOCK_DATA to true to enable
export const USE_MOCK_DATA = true;

import type { Incident, Video, TimelineEvent } from "@/types/api";

// Generate timestamps relative to now
const now = new Date();
const minutesAgo = (mins: number) => new Date(now.getTime() - mins * 60 * 1000).toISOString();
const hoursAgo = (hrs: number) => new Date(now.getTime() - hrs * 60 * 60 * 1000).toISOString();

export const mockIncidents: Incident[] = [
  {
    id: "inc-001",
    status: "active",
    lat: 37.7749,
    lng: -122.4194,
    startedAt: minutesAgo(15),
    createdAt: minutesAgo(15),
    updatedAt: minutesAgo(2),
  },
  {
    id: "inc-002",
    status: "active",
    lat: 37.7849,
    lng: -122.4094,
    startedAt: minutesAgo(45),
    createdAt: minutesAgo(45),
    updatedAt: minutesAgo(10),
  },
  {
    id: "inc-003",
    status: "resolved",
    lat: 37.7649,
    lng: -122.4294,
    startedAt: hoursAgo(2),
    createdAt: hoursAgo(2),
    updatedAt: minutesAgo(30),
  },
  {
    id: "inc-004",
    status: "active",
    lat: 37.7549,
    lng: -122.3994,
    startedAt: minutesAgo(5),
    createdAt: minutesAgo(5),
    updatedAt: minutesAgo(1),
  },
];

export const mockVideos: Video[] = [
  // Incident 1 videos
  {
    id: "vid-001",
    incidentId: "inc-001",
    status: "live",
    currentState: "Active car accident on Market Street. Two vehicles involved. Emergency responders on scene. One person appears to be receiving medical attention.",
    videoUrl: null,
    lat: 37.7749,
    lng: -122.4194,
    startedAt: minutesAgo(15),
    endedAt: null,
    createdAt: minutesAgo(15),
    updatedAt: minutesAgo(1),
  },
  {
    id: "vid-002",
    incidentId: "inc-001",
    status: "live",
    currentState: "Bystander footage from across the street. Shows traffic backup extending several blocks.",
    videoUrl: null,
    lat: 37.7751,
    lng: -122.4190,
    startedAt: minutesAgo(12),
    endedAt: null,
    createdAt: minutesAgo(12),
    updatedAt: minutesAgo(2),
  },
  // Incident 2 videos
  {
    id: "vid-003",
    incidentId: "inc-002",
    status: "live",
    currentState: "Small fire in residential building. Fire department actively working to contain. Smoke visible from upper floors.",
    videoUrl: null,
    lat: 37.7849,
    lng: -122.4094,
    startedAt: minutesAgo(45),
    endedAt: null,
    createdAt: minutesAgo(45),
    updatedAt: minutesAgo(5),
  },
  {
    id: "vid-004",
    incidentId: "inc-002",
    status: "ended",
    currentState: "Earlier footage showing fire start. Useful for investigation.",
    videoUrl: "https://example.com/recordings/vid-004.mp4",
    lat: 37.7848,
    lng: -122.4096,
    startedAt: minutesAgo(50),
    endedAt: minutesAgo(35),
    createdAt: minutesAgo(50),
    updatedAt: minutesAgo(35),
  },
  // Incident 3 videos (resolved)
  {
    id: "vid-005",
    incidentId: "inc-003",
    status: "recorded",
    currentState: "Medical emergency resolved. Patient transported to hospital.",
    videoUrl: "https://example.com/recordings/vid-005.mp4",
    lat: 37.7649,
    lng: -122.4294,
    startedAt: hoursAgo(2),
    endedAt: hoursAgo(1.5),
    createdAt: hoursAgo(2),
    updatedAt: minutesAgo(30),
  },
  // Incident 4 videos
  {
    id: "vid-006",
    incidentId: "inc-004",
    status: "live",
    currentState: "Suspicious activity reported. Individual matching description seen near entrance. Security notified.",
    videoUrl: null,
    lat: 37.7549,
    lng: -122.3994,
    startedAt: minutesAgo(5),
    endedAt: null,
    createdAt: minutesAgo(5),
    updatedAt: minutesAgo(1),
  },
];

// Timeline events for each video
export const mockTimelineEvents: Record<string, TimelineEvent[]> = {
  "vid-001": [
    {
      id: "evt-001-1",
      videoId: "vid-001",
      timestamp: minutesAgo(15),
      description: "Vehicle collision detected. Two sedans involved in intersection.",
      fromState: {},
      toState: { type: "carAccident", severity: "moderate" },
      confidence: 0.94,
      sourceSnapshots: ["snap-001"],
      createdAt: minutesAgo(15),
    },
    {
      id: "evt-001-2",
      videoId: "vid-001",
      timestamp: minutesAgo(12),
      description: "Person exiting vehicle, appears disoriented but mobile.",
      fromState: { type: "carAccident", severity: "moderate" },
      toState: { type: "carAccident", severity: "moderate", injuries: "minor" },
      confidence: 0.87,
      sourceSnapshots: ["snap-002"],
      createdAt: minutesAgo(12),
    },
    {
      id: "evt-001-3",
      videoId: "vid-001",
      timestamp: minutesAgo(10),
      description: "Emergency services arriving on scene. Fire truck visible.",
      fromState: { type: "carAccident" },
      toState: { type: "carAccident", responders: true },
      confidence: 0.98,
      sourceSnapshots: ["snap-003"],
      createdAt: minutesAgo(10),
    },
    {
      id: "evt-001-4",
      videoId: "vid-001",
      timestamp: minutesAgo(7),
      description: "Paramedics attending to one individual on stretcher.",
      fromState: { responders: true },
      toState: { responders: true, medicalAttention: true },
      confidence: 0.91,
      sourceSnapshots: ["snap-004"],
      createdAt: minutesAgo(7),
    },
    {
      id: "evt-001-5",
      videoId: "vid-001",
      timestamp: minutesAgo(4),
      description: "Traffic being redirected. Tow truck arriving.",
      fromState: { medicalAttention: true },
      toState: { medicalAttention: true, cleanup: "in_progress" },
      confidence: 0.89,
      sourceSnapshots: ["snap-005"],
      createdAt: minutesAgo(4),
    },
    {
      id: "evt-001-6",
      videoId: "vid-001",
      timestamp: minutesAgo(2),
      description: "Patient loaded into ambulance. Scene stabilizing.",
      fromState: { cleanup: "in_progress" },
      toState: { cleanup: "in_progress", patientTransported: true },
      confidence: 0.95,
      sourceSnapshots: ["snap-006"],
      createdAt: minutesAgo(2),
    },
  ],
  "vid-002": [
    {
      id: "evt-002-1",
      videoId: "vid-002",
      timestamp: minutesAgo(12),
      description: "Traffic backup observed extending 3+ blocks on Market St.",
      fromState: {},
      toState: { trafficImpact: "severe" },
      confidence: 0.92,
      sourceSnapshots: ["snap-010"],
      createdAt: minutesAgo(12),
    },
    {
      id: "evt-002-2",
      videoId: "vid-002",
      timestamp: minutesAgo(8),
      description: "Police setting up traffic cones, directing vehicles to alternate routes.",
      fromState: { trafficImpact: "severe" },
      toState: { trafficImpact: "severe", trafficControl: true },
      confidence: 0.88,
      sourceSnapshots: ["snap-011"],
      createdAt: minutesAgo(8),
    },
  ],
  "vid-003": [
    {
      id: "evt-003-1",
      videoId: "vid-003",
      timestamp: minutesAgo(45),
      description: "Smoke detected from third floor window of apartment building.",
      fromState: {},
      toState: { type: "fire", floor: 3 },
      confidence: 0.96,
      sourceSnapshots: ["snap-020"],
      createdAt: minutesAgo(45),
    },
    {
      id: "evt-003-2",
      videoId: "vid-003",
      timestamp: minutesAgo(40),
      description: "Fire department on scene. Ladder truck positioning.",
      fromState: { type: "fire" },
      toState: { type: "fire", responders: true },
      confidence: 0.99,
      sourceSnapshots: ["snap-021"],
      createdAt: minutesAgo(40),
    },
    {
      id: "evt-003-3",
      videoId: "vid-003",
      timestamp: minutesAgo(30),
      description: "Residents evacuating building. Fire appears contained to single unit.",
      fromState: { type: "fire", responders: true },
      toState: { type: "fire", responders: true, evacuation: true, contained: true },
      confidence: 0.85,
      sourceSnapshots: ["snap-022"],
      createdAt: minutesAgo(30),
    },
    {
      id: "evt-003-4",
      videoId: "vid-003",
      timestamp: minutesAgo(15),
      description: "Firefighters entering building with hoses. Smoke decreasing.",
      fromState: { contained: true },
      toState: { contained: true, activeSupression: true },
      confidence: 0.93,
      sourceSnapshots: ["snap-023"],
      createdAt: minutesAgo(15),
    },
  ],
  "vid-004": [
    {
      id: "evt-004-1",
      videoId: "vid-004",
      timestamp: minutesAgo(50),
      description: "Initial smoke visible from window. Small flames detected.",
      fromState: {},
      toState: { type: "fire", stage: "initial" },
      confidence: 0.91,
      sourceSnapshots: ["snap-030"],
      createdAt: minutesAgo(50),
    },
    {
      id: "evt-004-2",
      videoId: "vid-004",
      timestamp: minutesAgo(47),
      description: "Flames spreading. Building alarm audible.",
      fromState: { stage: "initial" },
      toState: { stage: "spreading", alarmActive: true },
      confidence: 0.94,
      sourceSnapshots: ["snap-031"],
      createdAt: minutesAgo(47),
    },
  ],
  "vid-005": [
    {
      id: "evt-005-1",
      videoId: "vid-005",
      timestamp: hoursAgo(2),
      description: "Person collapsed on sidewalk. Bystanders gathering.",
      fromState: {},
      toState: { type: "medical", personDown: true },
      confidence: 0.97,
      sourceSnapshots: ["snap-040"],
      createdAt: hoursAgo(2),
    },
    {
      id: "evt-005-2",
      videoId: "vid-005",
      timestamp: hoursAgo(1.9),
      description: "Bystander performing CPR. Someone on phone with 911.",
      fromState: { personDown: true },
      toState: { personDown: true, cprInProgress: true, emergencyCalled: true },
      confidence: 0.89,
      sourceSnapshots: ["snap-041"],
      createdAt: hoursAgo(1.9),
    },
    {
      id: "evt-005-3",
      videoId: "vid-005",
      timestamp: hoursAgo(1.75),
      description: "Ambulance arrived. Paramedics taking over.",
      fromState: { cprInProgress: true },
      toState: { paramedicsCare: true },
      confidence: 0.98,
      sourceSnapshots: ["snap-042"],
      createdAt: hoursAgo(1.75),
    },
    {
      id: "evt-005-4",
      videoId: "vid-005",
      timestamp: hoursAgo(1.5),
      description: "Patient stabilized and loaded into ambulance. Departing scene.",
      fromState: { paramedicsCare: true },
      toState: { transported: true, resolved: true },
      confidence: 0.96,
      sourceSnapshots: ["snap-043"],
      createdAt: hoursAgo(1.5),
    },
  ],
  "vid-006": [
    {
      id: "evt-006-1",
      videoId: "vid-006",
      timestamp: minutesAgo(5),
      description: "Suspicious individual detected near building entrance. Matching reported description.",
      fromState: {},
      toState: { type: "suspicious", threatLevel: "moderate" },
      confidence: 0.78,
      sourceSnapshots: ["snap-050"],
      createdAt: minutesAgo(5),
    },
    {
      id: "evt-006-2",
      videoId: "vid-006",
      timestamp: minutesAgo(3),
      description: "Individual looking into parked vehicles. Trying door handles.",
      fromState: { threatLevel: "moderate" },
      toState: { threatLevel: "elevated", behavior: "vehicle_tampering" },
      confidence: 0.85,
      sourceSnapshots: ["snap-051"],
      createdAt: minutesAgo(3),
    },
    {
      id: "evt-006-3",
      videoId: "vid-006",
      timestamp: minutesAgo(1),
      description: "Security guard approaching individual. Individual appears to be leaving area.",
      fromState: { behavior: "vehicle_tampering" },
      toState: { securityResponding: true, subjectFleeing: true },
      confidence: 0.82,
      sourceSnapshots: ["snap-052"],
      createdAt: minutesAgo(1),
    },
  ],
};

// Helper to get timeline events for a video
export function getMockTimelineEvents(videoId: string): TimelineEvent[] {
  return mockTimelineEvents[videoId] || [];
}
